"""Render a brief.md (winning-ad patterns + new ad concepts) into a styled PDF.

The markdown the tiktok-ad-brief skill writes is a small subset: headings,
bullet and numbered lists, bold/italic/inline-code, and paragraphs. This module
converts that subset to HTML and reuses report.render_pdf to make the PDF, so
md_to_html stays pure and testable while rendering shares one chromium path.
"""

import html
import os

import markdown

from tiktok_ads.report import render_pdf


def md_to_html(md_text):
    """Convert the brief markdown to an HTML body string.

    Uses the markdown library so nested and numbered lists, bold, and inline
    code all render correctly. A hand-rolled converter flattened nested bullets
    and restarted numbering on each concept, which made several ideas read as
    one.
    """
    return markdown.markdown(md_text, extensions=["extra", "sane_lists"])


def build_brief_html(md_text, title="New Ad Concepts"):
    """Build the full styled HTML page for a brief."""
    return (
        _BRIEF_TEMPLATE
        .replace("__TITLE__", html.escape(title))
        .replace("__BODY__", md_to_html(md_text))
    )


def default_brief_pdf_path(md_path):
    """Return the markdown path with a .pdf extension."""
    base, _ = os.path.splitext(md_path)
    return base + ".pdf"


def render_brief_pdf(md_path, out_path=None, title="New Ad Concepts"):
    """Read a brief.md, build HTML, and render it to a PDF. Returns the path."""
    with open(md_path, encoding="utf-8") as handle:
        md_text = handle.read()
    out_path = out_path or default_brief_pdf_path(md_path)
    return render_pdf(build_brief_html(md_text, title=title), out_path)


_BRIEF_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>__TITLE__</title>
<style>
  :root {
    --accent: #7e57c2;
    --accent-dark: #2a2140;
    --ink: #1f2330;
    --muted: #6b7280;
    --line: #e6e6ef;
  }
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
      Helvetica, Arial, "Apple Color Emoji", "Segoe UI Emoji", sans-serif;
    color: var(--ink);
    margin: 0;
    padding: 0 0 48px;
    font-size: 13px;
    line-height: 1.6;
  }
  .band {
    background: linear-gradient(120deg, var(--accent-dark), var(--accent));
    color: #fff;
    padding: 28px 40px;
  }
  .band h1 { margin: 0; font-size: 22px; font-weight: 700; }
  .band p { margin: 6px 0 0; opacity: 0.85; font-size: 12px; }
  .wrap { padding: 4px 40px; max-width: 840px; }
  .wrap h1 { font-size: 19px; color: var(--accent-dark); margin: 24px 0 10px; }
  .wrap h2 {
    font-size: 16px; color: var(--accent-dark); margin: 26px 0 8px;
    padding-bottom: 6px; border-bottom: 2px solid var(--line);
  }
  .wrap h3 { font-size: 13.5px; color: var(--accent); margin: 18px 0 4px; }
  .wrap h4 { font-size: 12.5px; color: var(--accent); margin: 14px 0 4px; }
  p { margin: 8px 0; }
  ul, ol { margin: 8px 0; padding-left: 22px; }
  li { margin: 3px 0; }
  code { background: #f3f0fa; padding: 1px 5px; border-radius: 4px; font-size: 12px; }
  strong { color: var(--ink); }
  hr { border: none; border-top: 1px solid var(--line); margin: 20px 0; }
  .foot { margin: 32px 40px 0; color: var(--muted); font-size: 10.5px; }
</style>
</head>
<body>
  <div class="band">
    <h1>__TITLE__</h1>
    <p>Creative patterns and new ad concepts from the TikTok Ads Library</p>
  </div>
  <div class="wrap">__BODY__</div>
  <p class="foot">
    Generated by tiktok_ads_scraper from public TikTok Ads Library data.
    Concepts are AI-generated suggestions grounded in the scraped winners.
  </p>
</body>
</html>
"""
